### ISSUE TITLE
Cannot start nuxt

### ISSUE THREAD

**Issue by attraction11** [productdevbook/oku-nuxt3-template#101]
### Environment

执行yarn run dev

### Describe the bug

Cannot read properties of undefined (reading 'resolveAlias') 

### Logs

Nuxi 3.0.0-rc.12                                                                                                                                                              18:26:43  
Nuxt 3.0.0-rc.12 with Nitro 0.6.0                                                                                                                                             18:26:43  
[get-port] Unable to find an available port (tried 3000). Using alternative port: 3001                                                                                        18:26:43  
                                                                                                                                                                              18:26:44  
  > Local:    http://localhost:3001/
  > Network:  http://10.9.97.66:3001/
  > Network:  http://192.168.110.106:3001/

i Using Tailwind CSS from ~/assets/css/tailwind.css                                                                                                          nuxt:tailwindcss 18:26:44  

 ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'resolveAlias')                                                                                      18:26:45

  at Object._default (C:/Users/Administrator/Downloads/oku-nuxt3-template-master/oku-nuxt3-template-master/node_modules/@nuxtjs/i18n/src/index.js:34:42)
  at installModule (/C:/Users/Administrator/Downloads/oku-nuxt3-template-master/oku-nuxt3-template-master/node_modules/@nuxt/kit/dist/index.mjs:456:20)
  at async initNuxt (/C:/Users/Administrator/Downloads/oku-nuxt3-template-master/oku-nuxt3-template-master/node_modules/nuxt/dist/index.mjs:1686:7)
  at async load (/C:/Users/Administrator/Downloads/oku-nuxt3-template-master/oku-nuxt3-template-master/node_modules/nuxi/dist/chunks/dev.mjs:6778:9)
  at async Object.invoke (/C:/Users/Administrator/Downloads/oku-nuxt3-template-master/oku-nuxt3-template-master/node_modules/nuxi/dist/chunks/dev.mjs:6828:5)
  at async _main (/C:/Users/Administrator/Downloads/oku-nuxt3-template-master/oku-nuxt3-template-master/node_modules/nuxi/dist/cli.mjs:50:20)

_No response_

**Comment by productdevbook** [comment]
can you try my new version again
